export const ENV = {
  DEV: process.env.NEXT_PUBLIC_ENV_DEVELOP,
  PROD: process.env.NEXT_PUBLIC_ENV_PRODUCTION,
  KEY_DEV: process.env.NEXT_PUBLIC_KEY_DEVELOP,
  KEY_PROD: process.env.NEXT_PUBLIC_KEY_PRODUCTION,
  GOOGLE_MAPS_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
  GOOGLE_MAPS_MAP_ID: process.env.NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID,
  KAKAO_JS_SDK_SRC: process.env.NEXT_PUBLIC_KAKAO_JS_SDK_SRC,
  KAKAO_JS_SDK_INTEGRITY: process.env.NEXT_PUBLIC_KAKAO_JS_SDK_INTEGRITY,
  KAKAO_REST_API_KEY: process.env.NEXT_PUBLIC_KAKAO_REST_API_KEY,
  KAKAO_JAVASCRIPT_KEY: process.env.NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY
};
