import { Libraries } from '@react-google-maps/api';

import { PlacesType } from '@/apis/services/google/places/type';
import { Transport } from '@/apis/types/common';
import { DropdownList } from '@/components/common/dropdowns/type';
import { Coordinate } from '@/components/features/maps/type';
import { ENV } from '@/libs/constants/env';

// 구글맵 API
export const GOOGLE_MAPS = {
  API_KEY: ENV.GOOGLE_MAPS_API_KEY || '',
  MAP_ID: ENV.GOOGLE_MAPS_MAP_ID || ''
};

// 맵 최대 줌 레벨
export const MAX_ZOOM = 20;

// 맵 초기 위치
export const DEFAULT_COORDINATE_LIST: Coordinate[] = [
  { lat: 35.68123620000001, lng: 139.7671248 } // 도쿄
];

// 라이브러리 목록
export const LIBRARIES: Libraries = ['places', 'marker'];

// Directions API 이동 수단 목록
export const TRANSPORT_DROPDOWN_LIST: DropdownList<object, Transport, Transport> = [
  { key: '자동차', value: '자동차' },
  { key: '도보', value: '도보' },
  { key: '자전거', value: '자전거' },
  { key: '대중교통', value: '대중교통' }
];

// 한국어로 번역
export const PLACE_TYPES: Record<PlacesType, string> & { unknown: string } = {
  // TypeA
  accounting: '회계',
  airport: '공항',
  american_restaurant: '미국식 레스토랑',
  amusement_center: '오락 센터',
  amusement_park: '놀이공원',
  aquarium: '수족관',
  art_gallery: '미술관',
  athletic_field: '운동장',
  atm: 'ATM',
  auto_parts_store: '자동차 부품 매장',
  bakery: '베이커리',
  bank: '은행',
  banquet_hall: '연회장',
  bar: '바',
  barber_shop: '이발소',
  barbecue_restaurant: '바베큐 레스토랑',
  beauty_salon: '미용실',
  bed_and_breakfast: 'B&B 숙소',
  bicycle_store: '자전거 가게',
  book_store: '서점',
  bowling_alley: '볼링장',
  brazilian_restaurant: '브라질 레스토랑',
  breakfast_restaurant: '조식 레스토랑',
  brunch_restaurant: '브런치 레스토랑',
  bus_station: '버스 정류장',
  bus_stop: '버스 정류소',
  cafe: '카페',
  camping_cabin: '캠핑 캐빈',
  campground: '캠핑장',
  car_dealer: '자동차 딜러',
  car_rental: '렌터카',
  car_repair: '자동차 수리',
  car_wash: '세차장',
  casino: '카지노',
  cell_phone_store: '휴대폰 매장',
  cemetery: '묘지',
  child_care_agency: '보육 기관',
  chinese_restaurant: '중식당',
  church: '교회',
  city_hall: '시청',
  clothing_store: '의류 매장',
  coffee_shop: '커피숍',
  community_center: '커뮤니티 센터',
  consultant: '컨설턴트',
  convention_center: '컨벤션 센터',
  convenience_store: '편의점',
  cottage: '별장',
  courthouse: '법원',
  courier_service: '택배 서비스',
  cultural_center: '문화센터',
  dental_clinic: '치과 의원',
  dentist: '치과',
  department_store: '백화점',
  discount_store: '할인 매장',
  doctor: '의사',
  dog_park: '애견 공원',
  drugstore: '약국',
  electric_vehicle_charging_station: '전기차 충전소',
  electrician: '전기공',
  electronics_store: '전자제품 매장',
  embassy: '대사관',
  event_venue: '행사장',
  extended_stay_hotel: '장기 숙박 호텔',
  farm: '농장',
  farmstay: '농장 숙박',
  fast_food_restaurant: '패스트푸드점',
  ferry_terminal: '페리 터미널',
  fire_station: '소방서',
  fitness_center: '피트니스 센터',
  florist: '꽃집',
  french_restaurant: '프랑스 레스토랑',
  funeral_home: '장례식장',
  furniture_store: '가구 매장',
  gas_station: '주유소',
  gift_shop: '선물 가게',
  golf_course: '골프장',
  greek_restaurant: '그리스 레스토랑',
  grocery_store: '식료품점',
  guest_house: '게스트하우스',
  gym: '체육관',
  hair_care: '미용 관리',
  hair_salon: '미용실',
  hamburger_restaurant: '햄버거 레스토랑',
  hardware_store: '철물점',
  heliport: '헬기장',
  hiking_area: '하이킹 지역',
  hindu_temple: '힌두 사원',
  historical_landmark: '역사적 명소',
  home_goods_store: '가정용품 매장',
  home_improvement_store: '인테리어 매장',
  hostel: '호스텔',
  hospital: '병원',
  hotel: '호텔',
  ice_cream_shop: '아이스크림 가게',
  indian_restaurant: '인도 레스토랑',
  indonesian_restaurant: '인도네시아 레스토랑',
  insurance_agency: '보험 대리점',
  italian_restaurant: '이탈리아 레스토랑',
  japanese_restaurant: '일식당',
  jewelry_store: '보석 상점',
  korean_restaurant: '한식당',
  laundry: '세탁소',
  lawyer: '변호사',
  lebanese_restaurant: '레바논 레스토랑',
  library: '도서관',
  light_rail_station: '경전철 역',
  liquor_store: '주류 판매점',
  local_government_office: '지방 정부 사무소',
  locksmith: '자물쇠 수리공',
  lodging: '숙박 시설',
  marina: '마리나',
  market: '시장',
  meal_delivery: '음식 배달',
  meal_takeaway: '테이크아웃',
  medical_lab: '의료 검사소',
  mediterranean_restaurant: '지중해식 레스토랑',
  mexican_restaurant: '멕시코 레스토랑',
  middle_eastern_restaurant: '중동 레스토랑',
  mosque: '모스크',
  motel: '모텔',
  movie_rental: '비디오 대여',
  movie_theater: '영화관',
  moving_company: '이사업체',
  museum: '박물관',
  national_park: '국립공원',
  night_club: '나이트클럽',
  painter: '화가',
  park: '공원',
  park_and_ride: '환승주차장',
  parking: '주차장',
  performing_arts_theater: '공연 예술 극장',
  pet_store: '애완동물 가게',
  pharmacy: '약국',
  physiotherapist: '물리치료사',
  pizza_restaurant: '피자 레스토랑',
  playground: '놀이터',
  plumber: '배관공',
  police: '경찰서',
  post_office: '우체국',
  preschool: '유치원',
  primary_school: '초등학교',
  private_guest_room: '개인 객실',
  ramen_restaurant: '라면 레스토랑',
  real_estate_agency: '부동산 중개소',
  resort_hotel: '리조트 호텔',
  rest_stop: '휴게소',
  restaurant: '레스토랑',
  roofing_contractor: '지붕 공사업자',
  rv_park: 'RV 공원',
  sandwich_shop: '샌드위치 가게',
  school: '학교',
  school_district: '학군',
  seafood_restaurant: '해산물 레스토랑',
  secondary_school: '중고등학교',
  shoe_store: '신발 매장',
  shopping_mall: '쇼핑몰',
  ski_resort: '스키 리조트',
  spa: '스파',
  spanish_restaurant: '스페인 레스토랑',
  sporting_goods_store: '스포츠 용품점',
  sports_club: '스포츠 클럽',
  sports_complex: '스포츠 컴플렉스',
  stadium: '경기장',
  steak_house: '스테이크 하우스',
  storage: '창고',
  store: '가게',
  subway_station: '지하철 역',
  supermarket: '슈퍼마켓',
  sushi_restaurant: '초밥집',
  swimming_pool: '수영장',
  synagogue: '유대교 회당',
  tailor: '재단사',
  taxi_stand: '택시 승강장',
  telecommunications_service_provider: '통신 서비스 제공업체',
  thai_restaurant: '태국 레스토랑',
  tourist_attraction: '관광 명소',
  train_station: '기차역',
  transit_depot: '교통 차고지',
  transit_station: '환승역',
  travel_agency: '여행사',
  truck_stop: '트럭 휴게소',
  turkish_restaurant: '터키 레스토랑',
  university: '대학교',
  vegan_restaurant: '비건 레스토랑',
  vegetarian_restaurant: '채식 레스토랑',
  veterinary_care: '수의사',
  vietnamese_restaurant: '베트남 레스토랑',
  visitor_center: '방문자 센터',
  wedding_venue: '웨딩 장소',
  wholesaler: '도매상',
  zoo: '동물원',
  administrative_area_level_1: '1차 행정구역',
  administrative_area_level_2: '2차 행정구역',
  country: '국가',
  locality: '지역',
  postal_code: '우편번호',
  //TypeB
  administrative_area_level_3: '3차 행정구역',
  administrative_area_level_4: '4차 행정구역',
  administrative_area_level_5: '5차 행정구역',
  administrative_area_level_6: '6차 행정구역',
  administrative_area_level_7: '7차 행정구역',
  archipelago: '군도',
  colloquial_area: '통칭 지역',
  continent: '대륙',
  establishment: '시설',
  finance: '금융',
  floor: '층',
  food: '음식',
  general_contractor: '종합 건설업체',
  geocode: '지오코드',
  health: '건강',
  intersection: '교차로',
  landmark: '랜드마크',
  natural_feature: '자연 지형',
  neighborhood: '근린',
  place_of_worship: '종교 시설',
  plus_code: '플러스 코드',
  point_of_interest: '관심 장소',
  political: '행정구역',
  post_box: '우편함',
  postal_code_prefix: '우편번호 접두사',
  postal_code_suffix: '우편번호 접미사',
  postal_town: '우편 행정구',
  premise: '구내',
  room: '방',
  route: '도로',
  street_address: '도로명 주소',
  street_number: '건물 번호',
  sublocality: '하위 지역',
  sublocality_level_1: '1차 하위 지역',
  sublocality_level_2: '2차 하위 지역',
  sublocality_level_3: '3차 하위 지역',
  sublocality_level_4: '4차 하위 지역',
  sublocality_level_5: '5차 하위 지역',
  subpremise: '하위 구내',
  town_square: '광장',
  // ETC
  unknown: '기타'
};
