const CITIES = [
  { id: 'Tokyo', korean: '도쿄', imageURL: 'https://flagcdn.com/w320/jp.png' },
  { id: 'Fukuoka', korean: '후쿠오카', imageURL: 'https://flagcdn.com/w320/jp.png' },
  { id: 'Osaka', korean: '오사카', imageURL: 'https://flagcdn.com/w320/jp.png' },
  { id: 'Kagoshima', korean: '가고시마', imageURL: 'https://flagcdn.com/w320/jp.png' },
  { id: 'Shizuoka', korean: '시즈오카', imageURL: 'https://flagcdn.com/w320/jp.png' },
  { id: 'Nagoya', korean: '나고야', imageURL: 'https://flagcdn.com/w320/jp.png' },
  { id: 'Sapporo', korean: '삿포로', imageURL: 'https://flagcdn.com/w320/jp.png' },
  { id: 'Okinawa', korean: '오키나와', imageURL: 'https://flagcdn.com/w320/jp.png' },
  { id: 'Nagasaki', korean: '나가사키', imageURL: 'https://flagcdn.com/w320/jp.png' },
  { id: 'Takamatsu', korean: '다카마쓰', imageURL: 'https://flagcdn.com/w320/jp.png' },
  { id: 'Nha Trang', korean: '나트랑', imageURL: 'https://flagcdn.com/w320/vn.png' },
  { id: 'Manila', korean: '마닐라', imageURL: 'https://flagcdn.com/w320/ph.png' },
  { id: 'Myanmar', korean: '미얀마', imageURL: 'https://flagcdn.com/w320/mm.png' },
  { id: 'Chiang Mai', korean: '치앙마이', imageURL: 'https://flagcdn.com/w320/th.png' },
  { id: 'Phila Wan', korean: '필라완', imageURL: 'https://flagcdn.com/w320/ph.png' },
  { id: 'Phu Quoc', korean: '푸꾸옥', imageURL: 'https://flagcdn.com/w320/vn.png' },
  { id: 'Laos', korean: '라오스', imageURL: 'https://flagcdn.com/w320/la.png' },
  { id: 'Kuala Lumpur', korean: '쿠알라룸푸르', imageURL: 'https://flagcdn.com/w320/my.png' },
  { id: 'Da Lat', korean: '달랏', imageURL: 'https://flagcdn.com/w320/vn.png' },
  { id: 'Da Nang', korean: '다낭', imageURL: 'https://flagcdn.com/w320/vn.png' },
  { id: 'Bangkok', korean: '방콕', imageURL: 'https://flagcdn.com/w320/th.png' },
  { id: 'Cebu', korean: '세부', imageURL: 'https://flagcdn.com/w320/ph.png' },
  { id: 'Kota Kinabalu', korean: '코타키나발루', imageURL: 'https://flagcdn.com/w320/my.png' },
  { id: 'Singapore', korean: '싱가포르', imageURL: 'https://flagcdn.com/w320/sg.png' },
  { id: 'Hanoi', korean: '하노이', imageURL: 'https://flagcdn.com/w320/vn.png' },
  { id: 'Ho Chi Minh', korean: '호치민', imageURL: 'https://flagcdn.com/w320/vn.png' },
  { id: 'Bali', korean: '발리', imageURL: 'https://flagcdn.com/w320/id.png' },
  { id: 'Phuket', korean: '푸켓', imageURL: 'https://flagcdn.com/w320/th.png' },
  { id: 'Boracay', korean: '보라카이', imageURL: 'https://flagcdn.com/w320/ph.png' },
  { id: 'Sydney', korean: '시드니', imageURL: 'https://flagcdn.com/w320/au.png' },
  { id: 'Melbourne', korean: '멜버른', imageURL: 'https://flagcdn.com/w320/au.png' },
  { id: 'Guam', korean: '괌', imageURL: 'https://flagcdn.com/w320/gu.png' },
  { id: 'Saipan', korean: '사이판', imageURL: 'https://flagcdn.com/w320/mp.png' },
  { id: 'Granada', korean: '그라나다', imageURL: 'https://flagcdn.com/w320/es.png' },
  { id: 'Dubrovnik', korean: '두브로브니크', imageURL: 'https://flagcdn.com/w320/hr.png' },
  { id: 'Lisbon', korean: '리스본', imageURL: 'https://flagcdn.com/w320/pt.png' },
  { id: 'Milan', korean: '밀라노', imageURL: 'https://flagcdn.com/w320/it.png' },
  { id: 'Brussels', korean: '브뤼셀', imageURL: 'https://flagcdn.com/w320/be.png' },
  { id: 'Seville', korean: '세비야', imageURL: 'https://flagcdn.com/w320/es.png' },
  { id: 'Zagreb', korean: '자그레브', imageURL: 'https://flagcdn.com/w320/hr.png' },
  { id: 'Porto', korean: '포르투', imageURL: 'https://flagcdn.com/w320/pt.png' },
  { id: 'Helsinki', korean: '헬싱키', imageURL: 'https://flagcdn.com/w320/fi.png' },
  { id: 'Athens', korean: '아테네', imageURL: 'https://flagcdn.com/w320/gr.png' },
  { id: 'Nice', korean: '니스', imageURL: 'https://flagcdn.com/w320/fr.png' },
  { id: 'Paris', korean: '파리', imageURL: 'https://flagcdn.com/w320/fr.png' },
  { id: 'Prague', korean: '프라하', imageURL: 'https://flagcdn.com/w320/cz.png' },
  { id: 'Rome', korean: '로마', imageURL: 'https://flagcdn.com/w320/it.png' },
  { id: 'London', korean: '런던', imageURL: 'https://flagcdn.com/w320/gb.png' },
  { id: 'Barcelona', korean: '바르셀로나', imageURL: 'https://flagcdn.com/w320/es.png' },
  { id: 'Vienna', korean: '빈', imageURL: 'https://flagcdn.com/w320/at.png' },
  { id: 'Florence', korean: '피렌체', imageURL: 'https://flagcdn.com/w320/it.png' },
  { id: 'Interlaken', korean: '인터라켄', imageURL: 'https://flagcdn.com/w320/ch.png' },
  { id: 'Madrid', korean: '마드리드', imageURL: 'https://flagcdn.com/w320/es.png' },
  { id: 'Budapest', korean: '부다페스트', imageURL: 'https://flagcdn.com/w320/hu.png' },
  { id: 'Vladivostok', korean: '블라디보스토크', imageURL: 'https://flagcdn.com/w320/ru.png' },
  { id: 'Zurich', korean: '취리히', imageURL: 'https://flagcdn.com/w320/ch.png' },
  { id: 'Frankfurt', korean: '프랑크푸르트', imageURL: 'https://flagcdn.com/w320/de.png' },
  { id: 'Munich', korean: '뮌헨', imageURL: 'https://flagcdn.com/w320/de.png' },
  { id: 'Amsterdam', korean: '암스테르담', imageURL: 'https://flagcdn.com/w320/nl.png' },
  { id: 'Berlin', korean: '베를린', imageURL: 'https://flagcdn.com/w320/de.png' },
  { id: 'Vancouver', korean: '밴쿠버', imageURL: 'https://flagcdn.com/w320/ca.png' },
  { id: 'San Francisco', korean: '샌프란시스코', imageURL: 'https://flagcdn.com/w320/us.png' },
  { id: 'Seattle', korean: '시애틀', imageURL: 'https://flagcdn.com/w320/us.png' },
  { id: 'Toronto', korean: '토론토', imageURL: 'https://flagcdn.com/w320/ca.png' },
  { id: 'Hawaii', korean: '하와이', imageURL: 'https://flagcdn.com/w320/us.png' },
  { id: 'New York', korean: '뉴욕', imageURL: 'https://flagcdn.com/w320/us.png' },
  { id: 'L.A', korean: '로스앤젤레스', imageURL: 'https://flagcdn.com/w320/us.png' },
  { id: 'Cancun', korean: '칸쿤', imageURL: 'https://flagcdn.com/w320/mx.png' },
  { id: 'Dubai', korean: '두바이', imageURL: 'https://flagcdn.com/w320/ae.png' },
  { id: 'Istanbul', korean: '이스탄불', imageURL: 'https://flagcdn.com/w320/tr.png' },
  { id: 'Cappadocia', korean: '카파도키아', imageURL: 'https://flagcdn.com/w320/tr.png' },
  { id: 'Kaohsiung', korean: '가오슝', imageURL: 'https://flagcdn.com/w320/tw.png' },
  { id: 'Qingdao', korean: '칭다오', imageURL: 'https://flagcdn.com/w320/cn.png' },
  { id: 'Hainan', korean: '하이난', imageURL: 'https://flagcdn.com/w320/cn.png' },
  { id: 'Taipei', korean: '타이베이', imageURL: 'https://flagcdn.com/w320/tw.png' },
  { id: 'Shanghai', korean: '상하이', imageURL: 'https://flagcdn.com/w320/cn.png' },
  { id: 'Beijing', korean: '베이징', imageURL: 'https://flagcdn.com/w320/cn.png' }
];

export default CITIES;
