export const API_URLS = {
  API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  GOOGLE_PLACES_API: process.env.NEXT_PUBLIC_GOOGLE_PLACES_API_URL,
  GOOGLE_PLACES_KEY: process.env.NEXT_PUBLIC_GOOGLE_PLACES_API_KEY,
  KAKAO_KAPI_URL: process.env.NEXT_PUBLIC_KAKAO_KAPI_URL,
  KAKAO_KAUTH_URL: process.env.NEXT_PUBLIC_KAKAO_KAUTH_URL,
  KAKAO_REDIRECT_URL: process.env.NEXT_PUBLIC_KAKAO_REDIRECT_URI,
  KAKAO_CLIENT_ID: process.env.NEXT_PUBLIC_KAKAO_CLIENT_ID
};
