const API_URL = {
  TEST: process.env.NEXT_PUBLIC_API_URL_TEST,
  API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  GOOGLE_PLACES_API: process.env.NEXT_PUBLIC_GOOGLE_PLACES_API_URL
};

export default API_URL;
